import Anthropic from "@anthropic-ai/sdk";
import { execSync } from "child_process";
import { writeFileSync, readFileSync } from "fs";
import { createRequire } from "module";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

require("dotenv").config({ path: join(ROOT, ".env") });

const MANUAL = process.argv.includes("--manual");

const today = new Date().toLocaleDateString("en-US", {
  month: "long",
  day: "numeric",
  year: "numeric",
});

const PROMPT = `Today is ${today}. Search the web for the most important US financial market news from today or the last 24 hours.

Return ONLY a valid JSON object — no markdown fences, no explanation, nothing else. Use this exact shape:
{
  "date": "${today}",
  "headline": "<5-8 word punchy headline>",
  "subheadline": "<one specific stat or data point that supports the headline>",
  "hook": "<one sentence that hooks a retail investor emotionally>",
  "bullets": [
    {"icon": "<single emoji>", "title": "<3-5 word title>", "detail": "<one concrete stat or fact>"},
    {"icon": "<single emoji>", "title": "<3-5 word title>", "detail": "<one concrete stat or fact>"},
    {"icon": "<single emoji>", "title": "<3-5 word title>", "detail": "<one concrete stat or fact>"}
  ],
  "watchOut": "<one sentence: what level/threshold/date to watch and why>",
  "ctaText": "Follow for daily market moves"
}`;

async function fetchFromAPI() {
  const client = new Anthropic();
  console.log(`Fetching market data for ${today}...`);

  const response = await client.messages.create({
    model: "claude-opus-4-7",
    max_tokens: 1024,
    tools: [{ type: "web_search_20250305", name: "web_search" }],
    messages: [{ role: "user", content: PROMPT }],
  });

  const textBlock = response.content.find((b) => b.type === "text");
  if (!textBlock) {
    throw new Error("No text in response:\n" + JSON.stringify(response.content, null, 2));
  }

  const clean = textBlock.text.replace(/```json\n?|\n?```/g, "").trim();
  return JSON.parse(clean);
}

function fetchFromFile() {
  const inputPath = join(ROOT, "data-input.json");
  console.log(`Reading data-input.json...`);
  const raw = readFileSync(inputPath, "utf8");
  return JSON.parse(raw);
}

async function generate() {
  const parsed = MANUAL ? fetchFromFile() : await fetchFromAPI();

  const output = `// Auto-generated by scripts/generate.mjs — do not edit manually
export const todayData = ${JSON.stringify(parsed, null, 2)};
`;

  writeFileSync(join(ROOT, "src", "data.ts"), output);
  console.log("✓ src/data.ts updated");

  console.log("Rendering video...");
  execSync("npm run render", { stdio: "inherit", cwd: ROOT });
  console.log("✓ out/reel.mp4 ready");
}

generate().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
