// Generated by Claude — give me your script and I'll fill this in each day.
export const todayData = {
  date: "May 17, 2026",

  // Color scheme: "bullish" | "bearish" | "volatile" | "breaking"
  theme: "volatile" as "bullish" | "bearish" | "volatile" | "breaking",

  headline: "THE STRAIT IS SHUT.\n$113 OIL.",
  subheadline: "27% of the world's oil — almost none is getting through.",
  hook: "The world's most critical\noil artery just closed.",

  bullets: [
    { icon: "🛢️", title: "Oil Above $113",       detail: "Brent crude hit $114 after US forces destroyed Iranian boats attacking commercial ships." },
    { icon: "🏦", title: "Fed Can't Help",         detail: "Rates frozen at 3.5–3.75%. Prolonged oil above $100 could reignite inflation." },
    { icon: "🌍", title: "Alliances Fracturing",   detail: "China & Russia vetoed UN action. France & UK launched their own escort mission." },
  ],

  watchOut: "If ceasefire collapses and oil breaks $120 — consumer spending craters, emerging markets bleed, and energy stocks are the only winners.",
  ctaText: "Follow for daily market moves",

  heroImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1080&q=80",

  chart: {
    title: "Brent Crude — Past Week  ($/barrel)",
    data: [95, 98, 103, 109, 113],
    labels: ["Mon", "Tue", "Wed", "Thu", "Fri"],
  },

  // ── Subtitles ─────────────────────────────────────────────────────────────
  // from/durationInFrames at 30fps. I time these to your voiceover script.
  // ~130 words/min = 1 word every ~14 frames. Adjust if you speak faster.
  subtitles: [
    { text: "Yaar sun 👀",                       from: 30,  durationInFrames: 38 },
    { text: "Duniya ka sabse bada oil route...",  from: 70,  durationInFrames: 50 },
    { text: "BAND ho gaya.",                      from: 122, durationInFrames: 40 },
    { text: "Oil $113 pe hai 🛢️",                from: 165, durationInFrames: 45 },
    { text: "aur abhi bhi chadh raha hai.",       from: 212, durationInFrames: 50 },
    { text: "Fed kuch nahi karega.",              from: 480, durationInFrames: 45 },
    { text: "Inflation wapas aa sakti hai.",      from: 527, durationInFrames: 50 },
    { text: "Ek number watch kar —",             from: 1020, durationInFrames: 45 },
    { text: "$120.",                              from: 1067, durationInFrames: 35 },
    { text: "Uske upar gaya toh...",              from: 1104, durationInFrames: 45 },
    { text: "market ko sambhalna mushkil hai. 💀", from: 1151, durationInFrames: 55 },
  ],

  // ── GIF inserts ───────────────────────────────────────────────────────────
  // position: "center" | "top-right" | "bottom-right" | "top-left"
  gifs: [
    {
      url: "https://media.giphy.com/media/NTur7XlVDUdqM/giphy.gif", // "this is fine" dog 🔥
      from: 122,
      durationInFrames: 55,
      size: 380,
      position: "center" as "center" | "top-right" | "bottom-right" | "top-left",
    },
    {
      url: "https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif", // money on fire 💸
      from: 1067,
      durationInFrames: 70,
      size: 340,
      position: "bottom-right" as "center" | "top-right" | "bottom-right" | "top-left",
    },
  ],
};
