// Generated by Claude — script by Udbhav
export const todayData = {
  date: "May 17, 2026",
  theme: "bullish" as "bullish" | "bearish" | "volatile" | "breaking",

  headline: "Modi Ji Ki\nDiplomacy On Fire 🔥",
  subheadline: "Netherlands ke baad Sweden — defense + semiconductor double setting",
  hook: "Sweden ne Modi ji ko\nfighter jets ke saath\nwelcome kiya! ✈️🇮🇳",

  bullets: [
    {
      icon: "✈️",
      title: "Fighter Jet Escort!",
      detail: "Swedish Air Force ne PM Modi ka Gothenburg mein welcome kiya — Netherlands semiconductor deal ke theek baad!",
    },
    {
      icon: "🛡️",
      title: "Defense: HAL & BEL",
      detail: "Sweden ke Gripen jets India ko chahiye + unki top company ne India mein 100% fully-owned factory daali!",
    },
    {
      icon: "💻",
      title: "Semi + AI Corridor",
      detail: "Dutch + Swedish double deal! Tata Electronics aur KPIT ko watchlist mein daal lo — real stonk up incoming.",
    },
  ],

  watchOut:
    "Portfolio laal hai toh ghabrao mat — geopolitics samajhoge toh agla multibagger yahin milega! 💎",
  ctaText: "Follow for daily market moves",

  heroImage:
    "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=1080&q=80",

  chart: {
    title: "HAL Share Price — This Week  (₹)",
    data: [3180, 3250, 3320, 3390, 3450],
    labels: ["Mon", "Tue", "Wed", "Thu", "Fri"],
  },

  // ── Subtitles ──────────────────────────────────────────────────────────────
  // Timed at ~150 WPM (2.5 words/sec = 12 frames/word) — adjust if you speak faster
  subtitles: [
    // Hook scene (0–240)
    { text: "Bhai,",                                    from: 30,   durationInFrames: 20 },
    { text: "Modi ji ka European tour",                 from: 52,   durationInFrames: 45 },
    { text: "alag hi level par chal raha hai! 🔥",      from: 99,   durationInFrames: 52 },
    { text: "Kal Netherlands mein",                     from: 154,  durationInFrames: 36 },
    { text: "semiconductor deal khatam ✅",             from: 192,  durationInFrames: 40 },

    // Headline scene (240–570)
    { text: "aaj unka vimaan",                          from: 245,  durationInFrames: 36 },
    { text: "seedha Sweden ke Gothenburg mein!",        from: 283,  durationInFrames: 48 },
    { text: "Swedish Air Force ke ✈️",                  from: 334,  durationInFrames: 38 },
    { text: "fighter jets ke escort ke saath!",         from: 374,  durationInFrames: 52 },
    { text: "Ab Dalal Street ke degens,",               from: 430,  durationInFrames: 45 },
    { text: "asli paisa kahan ban raha hai? 💰",        from: 477,  durationInFrames: 50 },
    { text: "Do sectors par nazar rakho. 👀",           from: 530,  durationInFrames: 42 },

    // Bullet 1 — Defense (570–870)
    { text: "Pehla: Defense 🛡️",                       from: 578,  durationInFrames: 36 },
    { text: "Sweden Gripen jets",                       from: 616,  durationInFrames: 34 },
    { text: "India ko bechne ke liye",                  from: 652,  durationInFrames: 45 },
    { text: "mara ja raha hai —",                       from: 699,  durationInFrames: 38 },
    { text: "unki top company ne",                      from: 740,  durationInFrames: 38 },
    { text: "100% factory India mein daali! 🏭",        from: 780,  durationInFrames: 50 },
    { text: "HAL aur BEL ke bulls 📈",                  from: 833,  durationInFrames: 42 },
    { text: "seatbelt baandh lo! 🚀",                   from: 877,  durationInFrames: 40 },

    // Bullet 2 — Semiconductors (870–1170)
    { text: "Doosra: Semiconductors + AI 💻",           from: 878,  durationInFrames: 45 },
    { text: "Pehle Dutch company se setting ki,",       from: 925,  durationInFrames: 50 },
    { text: "ab Sweden ke saath",                       from: 977,  durationInFrames: 36 },
    { text: "AI corridor bana rahe hain! 🤝",           from: 1015, durationInFrames: 50 },
    { text: "Tata Electronics aur KPIT",                from: 1068, durationInFrames: 45 },
    { text: "watchlist mein daal lo 📋",                from: 1115, durationInFrames: 44 },

    // Bullet 3 — Stonks (1170–1470)
    { text: "kyunki yeh log",                           from: 1178, durationInFrames: 30 },
    { text: "real-life mein stonk up",                  from: 1210, durationInFrames: 40 },
    { text: "hone wale hain! 🚀📈",                     from: 1252, durationInFrames: 45 },
    { text: "Portfolio laal hai?",                      from: 1300, durationInFrames: 36 },
    { text: "Ghabrao mat 😌",                           from: 1338, durationInFrames: 36 },

    // Watch Out (1470–1860)
    { text: "Geopolitics samajhoge",                    from: 1480, durationInFrames: 40 },
    { text: "toh agla multibagger",                     from: 1522, durationInFrames: 40 },
    { text: "yahin milega! 💎",                         from: 1564, durationInFrames: 40 },
  ],

  // ── GIF inserts ────────────────────────────────────────────────────────────
  gifs: [
    {
      // Fighter jets escort reveal
      url: "https://media.giphy.com/media/3o6ZsYuBnNEk5CXYqc/giphy.gif",
      from: 334,
      durationInFrames: 85,
      size: 360,
      position: "top-right" as "center" | "top-right" | "bottom-right" | "top-left",
    },
    {
      // Stonks going up meme
      url: "https://media.giphy.com/media/YnkMcHgNIMW4Yfmjxr/giphy.gif",
      from: 1252,
      durationInFrames: 75,
      size: 380,
      position: "center" as "center" | "top-right" | "bottom-right" | "top-left",
    },
    {
      // "This is fine" dog — for the ghabrao mat moment
      url: "https://media.giphy.com/media/NTur7XlVDUdqM/giphy.gif",
      from: 1338,
      durationInFrames: 80,
      size: 340,
      position: "bottom-right" as "center" | "top-right" | "bottom-right" | "top-left",
    },
  ],
};
